---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: agents-system
spec:
  interval: 5m
  chart:
    spec:
      version: 9.4.1
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 1m
  values:
    # https://artifacthub.io/packages/helm/bitnami/keycloak?modal=values
    image:
      # registry: docker.io
      # repository: bitnami/keycloak
      tag: 18.0.2
    resources:
      # limits: {}
      requests:
        cpu: 500m
        memory: 1024Mi
    auth:
      adminUser: admin
      adminPassword: admin
    postgresql:
      enabled: true
      auth:
        username: keycloak
        password: keycloak
        database: keycloak
    logging:
      output: json
