---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-grafana
  namespace: flux-system
spec:
  interval: 15m
  path: ./oci/apps/observability/grafana/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: kind-flux-demo
  wait: true
