---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kind-flux-demo
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/jazzlyn/kind-flux-demo
  ref:
    branch: main
  secretRef:
    name: github-deploy-key
  ignore: |
    # exclude all
    /*
    # include kubernetes directory only
    !/kubernetes
