---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app i-see-dead-pods
  labels:
    helmrelease.flux.defaults.arpa/enabled: "true"
    helmrelease.flux.crds.arpa/enabled: "false"
spec:
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  # https://github.com/bjw-s/helm-charts/tree/main/charts/other/app-template
  # https://github.com/tyriis/i-see-dead-pods
  values:
    controllers:
      i-see-dead-pods:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "*/5 * * * *"
        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true

        containers:
          cron:
            image:
              repository: bitnami/kubectl
              tag: 1.31.1@sha256:b509ab6000477ebe788df3509a8c4177e91238ee3003f33edea0931be3794340
            command:
              - /bin/sh
              - -ec
              - |
                kubectl get pods \
                  --all-namespaces \
                  -o go-template \
                  --template='{{range .items}}{{printf "%s %s %s\n" .metadata.namespace .metadata.name .status.message}}{{end}}' \
                  | grep "Pod was terminated in response to imminent node shutdown." \
                  | awk '{print $1, $2}' \
                  | xargs -r -n2 kubectl delete pod -n || true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 10m
                memory: 10Mi

    serviceAccount:
      create: true
      name: *app
