---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app i-see-dead-pods
  labels:
    helmrelease.flux.defaults.arpa/enabled: "true"
    helmrelease.flux.crds.arpa/enabled: "false"
spec:
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    # https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
    # https://github.com/tyriis/i-see-dead-pods
    controller:
      type: cronjob
      cronjob:
        schedule: "*/5 * * * *"
    image:
      repository: ghcr.io/k8s-at-home/kubectl
      tag: v1.25.4@sha256:7c79e72d9b194e856e4cee0dabd0a30fc7b42863975ddb70bdffe5ac69ce2c17
    command:
      - /bin/sh
      - -ec
      - |
        kubectl get pods \
          --all-namespaces \
          -o go-template \
          --template='{{range .items}}{{printf "%s %s %s\n" .metadata.namespace .metadata.name .status.message}}{{end}}' \
          | grep "Pod was terminated in response to imminent node shutdown." \
          | awk '{print $1, $2}' \
          | xargs -r -n2 kubectl delete pod -n || true
    serviceAccount:
      create: true
      name: *app
    service:
      main:
        enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
