---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    # https://grafana.com/docs/loki/latest/configuration/
    # https://artifacthub.io/packages/helm/grafana/loki?modal=values
    # https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
    loki:
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: abc

      structuredConfig:
        auth_enabled: false

        memberlist:
          join_members: ["loki-memberlist"]

        limits_config:
          retention_period: 2d

        common:
          ring:
            instance_addr: 127.0.0.1
            kvstore:
              store: inmemory

        schema_config:
          configs:
            - from: "2022-11-01"
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: loki_index_
                period: 24h

        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://prometheus-alertmanager.svc.cluster.local:9093
          storage:
            type: local
            local:
              directory: /tmp/rules
          rule_path: /tmp/scratch

        compactor:
          working_directory: /var/loki/boltdb-shipper-compactor
          compaction_interval: 10m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150
          shared_store: filesystem

        ingester:
          max_chunk_age: 1h

        analytics:
          reporting_enabled: false

    # write:
    #   persistence:
    #     size: 10Gi
    #     storageClass: standard
    # read:
    #   persistence:
    #     size: 10Gi
    #     storageClass: standard

    gateway:
      enabled: true
      replicas: 3

    monitoring:
      serviceMonitor:
        enabled: false
      selfMonitoring:
        lokiCanary:
          enabled: false
        enabled: false
        grafanaAgent:
          installOperator: false
