---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: opensearch
spec:
  chart:
    spec:
      version: 2.26.1
      chart: opensearch
      sourceRef:
        kind: HelmRepository
        name: opensearch-charts
        namespace: flux-system
  interval: 15m
  # https://artifacthub.io/packages/helm/opensearch-project-helm-charts/opensearch?modal=values
  values:
    opensearchJavaOpts: -Xmx256M -Xms256M
    plugins:
      enabled: true
      installList:
        - repository-gcs
        - https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/releases/download/2.17.1.0/prometheus-exporter-2.17.1.0.zip
