---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  labels:
    helmrelease.flux.defaults.arpa/enabled: "true"
spec:
  chart:
    spec:
      chart: reloader
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
  # https://artifacthub.io/packages/helm/stakater/reloader?modal=values
  values:
    fullnameOverride: reloader
    podMonitor:
      enabled: true
    image:
      repository: localhost:5050/renovate-test
      tag: latest
      pullPolicy: Always
