---
# yamllint disable
# https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      slack_api_url: https://hooks.slack.com/services/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
    route:
      group_by: ["alertname", "job"]
      group_wait: 1s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "slack-notifications"
      routes:
        - receiver: "null"
          matchers:
            - alertname =~ "InfoInhibitor|Watchdog"

    # configure hook template for slack
    receivers:
      - name: "null"
      - name: "slack-notifications"
        slack_configs:
          - channel: "#testhooks"
            send_resolved: true
            icon_url: https://avatars3.githubusercontent.com/u/3380462
            title: |-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
            text: >-
              {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }} {{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
                *Description:* {{ .Annotations.description }}
                *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
                *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}
  # alertmanagerSpec:
  #   storage:
  #     volumeClaimTemplate:
  #       spec:
  #         storageClassName: standard
  #         accessModes: ["ReadWriteOnce"]
  #         resources:
  #           requests:
  #             storage: 1Gi
