---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
configurations:
  - kustomize-config.yaml
configMapGenerator:
  - name: alertmanager-values
    files:
      - values.yaml=alertmanager-values.yaml
  - name: prometheus-values
    files:
      - values.yaml=prometheus-values.yaml
