---
# https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values
prometheus:
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  prometheusSpec:
    replicas: 3
    enableAdminAPI: true
    retention: 10d
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: standard
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 50Gi
