---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-reloader
  namespace: flux-system
spec:
  interval: 15m
  path: ./kubernetes/apps/kube-tools/reloader/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kind-flux-demo
  wait: true
