---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-gotk-observability
  namespace: flux-system
spec:
  interval: 15m
  path: ./kubernetes/apps/flux-system/gotk/observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: kind-flux-demo
  wait: true
