---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-sync
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-sync
  interval: 15m
  path: ./kubernetes/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: kind-flux-demo
  decryption:
    provider: sops
    secretRef:
      name: age-key
