---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: integration-sync
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-sync
  interval: 15m
  path: ./kubernetes/envs/integration
  prune: true
  sourceRef:
    kind: GitRepository
    name: kind-flux-demo
