---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app opensearch
spec:
  interval: 15m
  # https://artifacthub.io/packages/helm/opensearch-project-helm-charts/opensearch?modal=values
  values:
    opensearchJavaOpts: -Xmx100M -Xms100M
    sysctl:
      enabled: false
    sysctlInit:
      enabled: true
    sysctlVmMaxMapCount: 262144
