---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
spec:
  interval: 15m
  chart:
    spec:
      chart: jenkins
      version: 5.7.6
      sourceRef:
        kind: HelmRepository
        name: jenkins-charts
        namespace: flux-system
  # https://artifacthub.io/packages/helm/jenkinsci/jenkins?modal=values
  values:
    controller:
      installPlugins:
        # renovate: depName=pipeline-utility-steps datasource=jenkins-plugins versioning=maven extractVersion=^(?<version>.*)$
        - pipeline-utility-steps:2.17.0
        # renovate: depName=nodejs datasource=jenkins-plugins versioning=maven extractVersion=^(?<version>.*)$
        - nodejs:1.6.2
        # renovate: depName=pipeline-groovy-lib datasource=jenkins-plugins versioning=maven extractVersion=^(?<version>.*)$
        - pipeline-groovy-lib:730.ve57b_34648c63
        # renovate: depName=git-client datasource=jenkins-plugins versioning=maven extractVersion=^(?<version>.*)$
        - git-client:6.1.0
        # renovate: depName=popper2-api datasource=jenkins-plugins versioning=maven extractVersion=^(?<version>.*)$
        - popper2-api:2.11.6-5
        # renovate: depName=data-tables-api datasource=jenkins-plugins versioning=maven extractVersion=^(?<version>.*)$
        - data-tables-api:2.0.8-1
        # renovate: depName=git-client datasource=jenkins-plugins versioning=maven extractVersion=^(?<version>.*)$
        - git-client:6.1.0
