---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
spec:
  interval: 15m
  chart:
    spec:
      chart: jenkins
      version: 5.6.5
      sourceRef:
        kind: HelmRepository
        name: jenkins-charts
        namespace: flux-system
  # https://artifacthub.io/packages/helm/jenkinsci/jenkins?modal=values
  values:
    controller:
      additionalPlugins:
        - slack:722.vd07f1ea_7ff40
        - terraform:1.0.9
