---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
spec:
  interval: 15m
  chart:
    spec:
      chart: jenkins
      version: 5.7.5
      sourceRef:
        kind: HelmRepository
        name: jenkins-charts
        namespace: flux-system
  # https://artifacthub.io/packages/helm/jenkinsci/jenkins?modal=values
  values:
    controller:
      installPlugins:
        # renovate: depName=script-security datasource=jenkins-plugins versioning=maven extractVersion=^(?<version>.*)$
        - script-security:1362.v67dc1f0e1b_b_3
