---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-sync
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-sync
  interval: 1m
  retryInterval: 5s
  timeout: 5m
  path: ./apps
  prune: true
  sourceRef:
    kind: OCIRepository
    name: kind-flux-demo
  decryption:
    provider: sops
    secretRef:
      name: age-key
