---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-sync
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  path: ./flux
  prune: true
  sourceRef:
    kind: OCIRepository
    name: kind-flux-demo
  decryption:
    provider: sops
    secretRef:
      name: age-key
