---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: opensearch
spec:
  chart:
    spec:
      version: 2.23.2
      chart: opensearch
  # https://artifacthub.io/packages/helm/opensearch-project-helm-charts/opensearch?modal=values
  values:
    opensearchJavaOpts: -Xmx512M -Xms512M
