---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../../base/opensearch/helm-release.yaml
patches:
  - path: helm-values.yaml
configMapGenerator:
  - name: opensearch-config
    behavior: create
    files:
      - opensearch.yml=opensearch.yaml
generatorOptions:
  disableNameSuffixHash: true
