---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-source.yaml
  - flux-sync.yaml
  - gotk-components.yaml

# service account for workload identity
# https://fluxcd.io/flux/guides/mozilla-sops/#encrypting-secrets-using-various-cloud-providers
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: kustomize-controller
      namespace: flux-system
      annotations:
        iam.gke.io/gcp-service-account: abc@abc.iam.gserviceaccount.com
