---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docusaurus
spec:
  interval: 5m
  chart:
    spec:
      chart: docusaurus
      version: 1.0.12
      sourceRef:
        kind: HelmRepository
        name: truecharts-charts
        namespace: flux-system
  install:
    crds: Skip
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    crds: Skip
    remediation:
      retries: 5
  values:
    image:
      tag: 2.1.0
    env:
      WEBSITE_NAME: "Docusaurus test site"
      TEMPLATE: classic
