---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: grafana
      version: 7.0.22
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    # https://artifacthub.io/packages/helm/grafana/grafana?modal=values
    env:
      TZ: ${SETTING_TZ}
      GF_EXPLORE_ENABLED: "true"
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: "true"
    grafana.ini:
      auth:
        oauth_auto_login: false
      auth.basic:
        enabled: true
      server:
        root_url: https://test.example.com/grafana
      users:
        auto_assign_org_role: Viewer
        viewers_can_edit: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        # list of datasources that should be deleted from the database
        deleteDatasources:
          - name: Loki
            orgId: 1
          - name: Prometheus
            orgId: 1
          - name: Tempo
            orgId: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://kube-prometheus-stack-prometheus:9090/
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-gateway:80/
          - name: Tempo
            type: tempo
            access: proxy
            url: http://tempo:3100/
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      # - natel-discrete-panel
      # - pr0ps-trackmap-panel
      - grafana-piechart-panel
      # - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
    serviceMonitor:
      enabled: true
    persistence:
      enabled: false
