---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ../../../../kind-flux-test/kubernetes/talos-flux/apps/observability/grafana/app
patchesStrategicMerge:
  - helm-values.yaml
