---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ../../../../kind-flux-demo/kubernetes/apps/observability/grafana/app
patches:
  - path: helm-values.yaml
