---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-opensearch
  namespace: flux-system
spec:
  interval: 15m
  path: ./kubernetes/apps/opensearch/opensearch/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kind-flux-demo
  wait: true
