---
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-init-job
spec:
  completions: 1
  template:
    metadata:
      name: keycloak-init
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:16.1.1
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: BITNAMI_DEBUG
          value: "false"
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: keycloak
        - name: KEYCLOAK_MANAGEMENT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: management-password
              name: keycloak
        - name: KEYCLOAK_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak-postgresql
        - name: KEYCLOAK_HTTP_RELATIVE_PATH
          value: /
        envFrom:
        - configMapRef:
            name: keycloak-env-vars
        command:
        - /bin/sh
        args: # yamllint disable-line rule:line-length
        - -c
        - |
          /opt/jboss/keycloak/bin/kcadm.sh update realms/master -s loginTheme=agents --server http://keycloak.namespace-demo.svc.cluster.local --realm master --user admin --password admin &&
          /opt/jboss/keycloak/bin/kcadm.sh create realms -s realm=testrealm -f resources/default-realm.json --server http://keycloak.namespace-demo.svc.cluster.local --realm master --user admin --password admin &&
          /opt/jboss/keycloak/bin/kcadm.sh create users -r testrealm -s username=admin -s enabled=true --server http://keycloak.namespace-demo.svc.cluster.local --realm master --user admin --password admin &&
          /opt/jboss/keycloak/bin/kcadm.sh set-password -r testrealm --username admin --new-password admin --temporary --server http://keycloak.namespace-demo.svc.cluster.local --realm master --user admin --password admin &&
          /opt/jboss/keycloak/bin/kcadm.sh add-roles -r testrealm --uusername admin --rolename view-topic-planning --rolename view-blacklist --rolename view-article-report --server http://keycloak.namespace-demo.svc.cluster.local --realm master --user admin --password admin &&
          /opt/jboss/keycloak/bin/kcadm.sh add-roles -r testrealm --uusername admin --cclientid realm-management --rolename manage-users --rolename view-users --server http://keycloak.namespace-demo.svc.cluster.local --realm master --user admin --password admin

        # - /opt/jboss/keycloak/bin/kcadm.sh create clients -r testrealm -s clientId=client-app -s enabled=true -s publicClient=true -s baseUrl=https://agents.integration.strg.at  -s adminUrl=https://agents.integration.strg.at  -s "redirectUris=[\"https://agents.integration.strg.at/*\"]" -s "webOrigins=[\"https://agents.integration.strg.at\"]" --server http://keycloak.namespace-demo.svc.cluster.local --realm master --user admin --password
      restartPolicy: OnFailure
