---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - keycloak-init-job-configmap-resources.yaml
  - keycloak-init-job-configmap-themes-***REMOVED***.yaml
  - keycloak-init-job.yaml
namespace: namespace-demo
