---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 10m
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  test:
    enable: false
  values:
    env:
      TEST1: test1
      TEST2: test2
      TEST3: test3
    hpa:
      enabled: true
      maxReplicas: 2
      cpu: 90
