---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 15m
  chart:
    spec:
      version: 0.16.2
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    # https://artifacthub.io/packages/helm/grafana/tempo?modal=values
    tempo:
      retention: 48h
    # persistence:
    #   enabled: true
    #   storageClassName: standard
    #   size: 10Gi
    serviceMonitor:
      enabled: true
