---
name: flux-diff

on:
  pull_request:
    branches:
      - main
    paths:
      - kubernetes/**.yaml

jobs:
  flux-diff:
    permissions:
      pull-requests: write
    uses: strg-at/github-workflows/.github/workflows/flux-diff.yaml@feature/AGENTS-1425-update-flux-diff
    with:
      runner: '["arc-runner-set-kind-flux-demo"]'
      path: '["kubernetes"]'
      source: kind-flux-demo
    secrets:
      github-app-id: "${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}"
      github-app-key: "${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}"
