---
name: flux-diff

on:
  pull_request:
    branches:
      - main
    paths:
      # - kubernetes/**.yaml
      - oci/**.yaml

# jobs:
#   flux-diff:
#     permissions:
#       pull-requests: write
#     uses: strg-at/github-workflows/.github/workflows/flux-diff.yaml@v1.3.1
#     with:
#       runner: '["ubuntu-latest"]'
#       paths: '["kubernetes"]'
#       resources: '["helmrelease", "kustomization"]'
#       #sources: kind-flux-demo
#     secrets:
#       github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
#       github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

jobs:
  flux-diff:
    runs-on: arc-runner-set-kind-flux-demo
    permissions:
      pull-requests: write
    strategy:
      matrix:
        paths: ["oci"]
        resources: ["helmrelease", "kustomization"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/github-app-token
      - name: generate token
        id: generate-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: "${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}"
          private_key: "${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}"

      # https://github.com/alexellis/arkade-get
      - name: install kube-tools
        uses: alexellis/arkade-get@962792902efae2ed77247127b044579f2e13fa8e
        with:
          print-summary: false
          flux: v2.2.2
          helm: v3.13.3
          kustomize: v5.3.0

      - name: setup docker
        uses: docker/setup-buildx-action@v3.0.0

      - name: start oci registry
        run: |
          docker run -d --rm --name kind-registry -p 5000:5050 registry:2.8.1
          sleep 10

      - name: push-artifact
        run: |
          flux push artifact oci://localhost:5050/kind-flux-demo:local \
            --path="oci" \
            --source="local" \
            --revision="latest"

      # https://github.com/allenporter/flux-local/tree/main/action/diff
      - name: diff resources
        uses: allenporter/flux-local/action/diff@d290eeb73abc46bd130aa32f4affd78d40806433 # 4.3.0
        id: diff
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          path: "${{ matrix.paths }}"
          resource: "${{ matrix.resources }}"
          sources: kind-flux-demo

      # https://github.com/marketplace/actions/add-pr-comment
      - name: add comment
        if: ${{ steps.diff.outputs.diff != '' }}
        uses: mshick/add-pr-comment@v2.8.1
        with:
          repo-token: "${{ steps.generate-token.outputs.token }}"
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.paths }}/${{ matrix.resources }}"
          message-failure: diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
