---
name: renovate

on:
  workflow_dispatch:
    inputs:
      log-level:
        description: "log-level (debug, info, warn, error, fatal)"
        required: false
        type: string
        default: "debug"
      dry-run:
        description: "dry-run (extract, lookup, full)"
        required: false
        type: string
        default: "null"
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate-bot.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    uses: strg-at/github-workflows/.github/workflows/run-renovate.yaml@fe8aec8df10849c97cc87d1d2e1448d03121aceb # v1.10.0
    permissions:
      contents: read
    with:
      runner: '["ubuntu-latest"]'
      configuration-file: .github/renovate-bot.json5
      dry-run: ${{ inputs.dry-run || 'null' }}
      log-level: ${{ inputs.log-level || 'debug' }}
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}
