---
name: renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: dry run mode
        type: choice
        options:
          - "null"
          - extract
          - lookup
          - full
        default: "null"
        required: false
      log-level:
        description: renovate log level
        type: choice
        options:
          - debug
          - info
          - warn
          - error
          - fatal
        default: debug
        required: false
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate-bot.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    uses: strg-at/github-workflows/.github/workflows/run-renovate.yaml@a6bef76273634bc3b14145c8c37c52dc21db7053 # v1.10.4
    permissions:
      contents: read
      pull-requests: write
    with:
      runner: '["ubuntu-latest"]'
      configuration-file: .github/renovate-bot.json5
      dry-run: ${{ inputs.dry-run || 'null' }}
      log-level: ${{ inputs.log-level || 'debug' }}
    secrets:
      github-app-id: ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}
