---
name: renovate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: dry-run
        required: false
        type: string
        default: "false"
      log-level:
        description: log-level
        required: false
        type: string
        default: info
  # schedule:
  #   - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5
      - .github/workflows/renovate.yaml

concurrency:
  group: renovate
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      # https://github.com/marketplace/actions/github-app-token
      - name: generate token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id:  ${{ secrets.JAZZLYN_BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.JAZZLYN_BOT_GITHUB_PEM }}

      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          token: ${{ steps.generate-token.outputs.token }}

      # https://github.com/marketplace/actions/renovate-bot-github-action
      - name: renovate bot
        uses: renovatebot/github-action@063e0c946b9c1af35ef3450efc44114925d6e8e6 # v40.1.11
        env:
          DRY_RUN: ${{ inputs.dry-run || 'false' }}
          LOG_LEVEL: ${{ inputs.log-level || 'info' }}
        with:
          token: ${{ steps.generate-token.outputs.token }}
          configurationFile: .github/renovate-bot.json5
